package com.example.temperatureservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-05-12T13:51:02.713+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.example.com/TemperatureService", name = "TempPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempPort {

    @WebMethod(operationName = "GetCelsius")
    @WebResult(name = "GetCelsiusResponse", targetNamespace = "http://www.example.com/TemperatureService", partName = "GetCelsiusResponse")
    public GetCelsiusResponse getCelsius(
        @WebParam(partName = "GetCelsiusRequest", name = "GetCelsiusRequest", targetNamespace = "http://www.example.com/TemperatureService")
        GetCelsiusRequest getCelsiusRequest
    );
}
