package com.example.temperatureservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-05-12T13:51:02.756+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "TempPortService", 
                  wsdlLocation = "file:/C:/workspace/spring-boot-soap-https-authentication-client/src/main/resources/wsdl/temp.wsdl",
                  targetNamespace = "http://www.example.com/TemperatureService") 
public class TempPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.com/TemperatureService", "TempPortService");
    public final static QName TempPortSoap11 = new QName("http://www.example.com/TemperatureService", "TempPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/spring-boot-soap-https-authentication-client/src/main/resources/wsdl/temp.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TempPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/spring-boot-soap-https-authentication-client/src/main/resources/wsdl/temp.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TempPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TempPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TempPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TempPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TempPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TempPort
     */
    @WebEndpoint(name = "TempPortSoap11")
    public TempPort getTempPortSoap11() {
        return super.getPort(TempPortSoap11, TempPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempPort
     */
    @WebEndpoint(name = "TempPortSoap11")
    public TempPort getTempPortSoap11(WebServiceFeature... features) {
        return super.getPort(TempPortSoap11, TempPort.class, features);
    }

}
