//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.12 at 01:47:41 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/TemperatureService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jeejava.jaxb;
