//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.26 at 05:45:28 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/TemperatureService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.roytuts.jaxb;
